In [49]:
# 1-1. 데이터 가져오기 

import pandas as pd 
import matplotlib.pyplot as plt 


socar = pd.read_csv('../../0. raw_data/insurance_fraud_detect_data.csv')
socar

,fraud_YN,car_model,sharing_type,age_group,has_previous_accident,cumulative_use_count,b2b,accident_ratio,pf_type,socarpass,...,insure_cost,accident_location,car_part1,car_part2,repair_cnt,acc_type1,insurance_site_aid_YN,police_site_aid_YN,total_prsn_cnt,test_set
0,0,2,1,3,0,2,0,100,2,0,...,0,1,0,0,1,0,0,0,-1,0
1,0,1,0,4,0,4,0,0,3,1,...,0,1,1,1,2,1,1,1,0,1
2,0,1,0,4,1,4,0,100,3,1,...,12925040,3,1,0,2,1,1,1,0,1
3,0,3,1,3,0,4,0,0,2,0,...,0,3,1,0,1,0,0,0,-1,0
4,0,1,0,1,0,1,0,100,1,0,...,1209410,1,0,0,2,0,0,0,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,0,2,0,2,0,2,0,100,2,0,...,0,1,1,0,1,0,0,0,-1,0
15996,0,2,0,2,1,4,0,100,1,1,...,0,2,1,0,1,0,0,0,-1,0
15997,0,2,1,2,0,4,0,100,1,0,...,0,0,0,0,1,0,0,0,-1,1
15998,0,2,0,2,0,2,0,100,2,0,...,0,4,1,0,1,0,0,0,-1,0
15999,0,2,0,2,0,1,0,100,1,0,...,1188750,2,0,0,1,0,0,0,-1,0

In [50]:
# 테스트 셋 분리

df = socar[socar['test_set']==0]
df_test = socar[socar['test_set']==1]

In [51]:
# test_set 분리 
X_test = df_test.drop('fraud_YN', axis = 1)
y_test = df_test['fraud_YN']

In [52]:
# train-valid 분리 

from sklearn.model_selection import train_test_split

y_target = df['fraud_YN']
X_features = df.drop('fraud_YN', axis = 1)

X_train, X_valid, y_train, y_valid = train_test_split(X_features, y_target, test_size = 0.2, random_state = 13, stratify = y_target)

# 비율 확인 
print(y_train.value_counts()/y_train.shape[0]*100) 
print(y_valid.value_counts()/y_valid.shape[0]*100)

0    99.73794
1     0.26206
Name: fraud_YN, dtype: float64
0    99.728261
1     0.271739
Name: fraud_YN, dtype: float64

In [73]:
# 학습 / 예측 / 평가 함수 

# 평가 함수 

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score

def get_clf_eval(y_test, pred):
    # confusion = confusion_matrix(y_test, pred) #오차행렬
    accuracy = accuracy_score(y_test,pred) # 정확도 
    precision = precision_score(y_test,pred) # 정밀도
    recall = recall_score(y_test,pred) # 재현율 
    f1 = f1_score(y_test,pred)
    roc_auc = roc_auc_score(y_test,pred)
    return accuracy, precision, recall, f1, roc_auc

# 성능 DF 반환 

def get_result(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    return get_clf_eval(y_test, pred)

# 다수의 모델 성능 비교 

def get_result_df(models, model_names, X_train, y_train, X_test, y_test):
    col_names = ['Accuracy', 'precision', 'recall', 'f1', 'roc']
    tmp = []
    for model in models:
        tmp.append(get_result(model, X_train, y_train, X_test, y_test))

    return pd.DataFrame(tmp, columns=col_names, index=model_names)


# 성능 확인 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import LinearSVC


# 모델 객체 생성 
lr_clf = LogisticRegression(random_state=13)
dt_clf = DecisionTreeClassifier(random_state=13, max_depth=4)
rf_clf = RandomForestClassifier(random_state=13, n_jobs = -1, n_estimators= 100 )
lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average = False)
svm_clf = LinearSVC()


# 학습 진행 
models=[lr_clf,dt_clf,rf_clf,lgbm_clf,svm_clf] 
model_names = ['LogiReg', 'DecisionTree', 'RandomFore','LGBM','SVC']
results = get_result_df(models, model_names, X_train, y_train, X_valid, y_valid)
results

              Accuracy  precision  recall   f1       roc
LogiReg       0.997283        0.0     0.0  0.0  0.500000
DecisionTree  0.996894        0.0     0.0  0.0  0.499805
RandomFore    0.996894        0.0     0.0  0.0  0.499805
LGBM          0.995730        0.0     0.0  0.0  0.499221
SVC           0.997283        0.0     0.0  0.0  0.500000

## Trial #1
- ssscale / pca(n=2) / smote-teen

In [54]:
# 모델 객체를 predict(X_test) 시켜줄 것 
df_1 = df.copy()

In [55]:
y_target = df_1['fraud_YN']
X_features = df_1.drop('fraud_YN', axis=1)

In [56]:
y_target = df_1['fraud_YN'].reset_index()
y_target = y_target.drop('index', axis=1)

In [57]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(X_features)

pca = PCA(n_components=2)
pca.fit(df_scaled)
df_pca = pca.transform(df_scaled)

pca_columns = ['component_1','component_2']

DF_pca = pd.DataFrame(df_pca, columns=pca_columns)
DF_pca['target'] = y_target 
DF_pca.tail()

       component_1  component_2  target
12874    -0.900409    -0.046252       0
12875    -1.223357     1.351087       0
12876    -0.676326     0.384020       0
12877    -1.383708     0.660141       0
12878    -1.286993    -1.025109       0

In [74]:
y_target = DF_pca['target']
X_features = DF_pca.drop('target', axis= 1)


X_train, X_valid, y_train, y_valid = train_test_split(X_features, y_target, test_size =0.2, random_state=13, stratify= y_target)

# 모델 객체 생성 
lr_clf = LogisticRegression(random_state=13)
dt_clf = DecisionTreeClassifier(random_state=13, max_depth=4)
rf_clf = RandomForestClassifier(random_state=13, n_jobs = -1, n_estimators= 100 )
lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average = False)
svm_clf = LinearSVC()

# 학습 진행 
models=[lr_clf,dt_clf,rf_clf,lgbm_clf,svm_clf] 
model_names = ['LogiReg', 'DecisionTree', 'RandomFore','LGBM','SVC']
results = get_result_df(models, model_names, X_train, y_train, X_valid, y_valid)
results

              Accuracy  precision  recall   f1       roc
LogiReg       0.997283        0.0     0.0  0.0  0.500000
DecisionTree  0.996894        0.0     0.0  0.0  0.499805
RandomFore    0.996894        0.0     0.0  0.0  0.499805
LGBM          0.995730        0.0     0.0  0.0  0.499221
SVC           0.997283        0.0     0.0  0.0  0.500000

In [59]:
# 복합 샘플링 적용 

from imblearn.combine import SMOTEENN
sme = SMOTEENN(random_state=13)
X_train_sme, y_train_sme = sme.fit_sample(X_train, y_train)


model_names = ['LogiReg', 'DecisionTree', 'RandomFore','LGBM','SVC']
results = get_result_df(models, model_names, X_train_sme, y_train_sme, X_valid, y_valid)

results

              Accuracy  precision    recall        f1       roc
LogiReg       0.654891   0.005605  0.714286  0.011123  0.684508
DecisionTree  0.477484   0.001489  0.285714  0.002963  0.381861
RandomFore    0.779891   0.001779  0.142857  0.003515  0.462242
LGBM          0.781832   0.001795  0.142857  0.003546  0.463215
SVC           0.670419   0.005869  0.714286  0.011641  0.692293

In [60]:
# 테스트셋 적용 
# PCA / ss 

df_test_scaled = scaler.transform(X_test)
df_test_pca = pca.transform(df_test_scaled)

pca_columns = ['component_1','component_2']

DF_test_pca = pd.DataFrame(df_pca, columns=pca_columns)
DF_test_pca['target'] = y_target 
DF_test_pca.tail()

X_test_scaled = DF_test_pca.drop('target', axis=1)
y_test_scaled = DF_test_pca['target']

In [81]:
# 다수의 모델 테스트 성능 비교 함수 

def get_test_result(model, X_test_scaled, y_test_scaled):
    pred = model.predict(X_test_scaled)
    return get_clf_eval(y_test_scaled, pred)

def get_test_df(models, model_names, X_test_scaled, y_test_scaled):
    col_names = ['Accuracy', 'precision', 'recall', 'f1', 'roc']
    tmp = []
    for model in models:
        tmp.append(get_test_result(model, X_test_scaled,y_test_scaled))
    return pd.DataFrame(tmp, columns=col_names, index=model_names)

In [83]:
# 테스트 셋 모델 적용 

models=[lr_clf,dt_clf,rf_clf,lgbm_clf,svm_clf] 
model_names = ['LogiReg', 'DecisionTree', 'RandomFore','LGBM','SVC']
results = get_test_df(models,model_names, X_test_scaled, y_test_scaled)
results

              Accuracy  precision    recall        f1       roc
LogiReg       0.997360   0.000000  0.000000  0.000000  0.500000
DecisionTree  0.997593   0.800000  0.117647  0.205128  0.558785
RandomFore    0.999379   0.964286  0.794118  0.870968  0.897020
LGBM          0.998835   0.851852  0.676471  0.754098  0.838080
SVC           0.997360   0.000000  0.000000  0.000000  0.500000

## Trial #2
## ssscale / pca(n=2) / smote-tomek

In [84]:
df_2 = df.copy()

y_target = df_2['fraud_YN']
X_features = df_2.drop('fraud_YN', axis = 1)

y_target = df_2['fraud_YN'].reset_index()
y_target = y_target.drop('index', axis=1)

In [85]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(X_features)

pca = PCA(n_components=3)
pca.fit(df_scaled)
df_pca = pca.transform(df_scaled)

pca_columns = ['component_1','component_2','component_3']

DF_pca = pd.DataFrame(df_pca, columns=pca_columns)
DF_pca['target'] = y_target 
DF_pca.head()

   component_1  component_2  component_3  target
0    -1.190720    -1.113793    -0.216083       0
1    -0.651287    -0.016829     1.454749       0
2    -1.355833     1.608717    -1.008398       0
3     4.345352    -0.901682     0.395155       1
4     3.897245    -1.945034     0.161711       0

In [87]:
y_target = DF_pca['target']
X_features = DF_pca.drop('target', axis= 1)


X_train, X_valid, y_train, y_valid = train_test_split(X_features, y_target, test_size =0.2, random_state=13, stratify= y_target)

# 모델 객체 생성 
lr_clf = LogisticRegression(random_state=13)
dt_clf = DecisionTreeClassifier(random_state=13, max_depth=4)
rf_clf = RandomForestClassifier(random_state=13, n_jobs = -1, n_estimators= 100 )
lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average = False)
svm_clf = LinearSVC()

# SMOKE + TOMEK 
from imblearn.combine import SMOTETomek
tmk = SMOTETomek(random_state =13)
X_train_tmk , y_train_tmk  = tmk.fit_sample(X_train,y_train)

models=[lr_clf,dt_clf,rf_clf,lgbm_clf,svm_clf] 
model_names = ['LogiReg', 'DecisionTree', 'RandomFore','LGBM','SVC']
results = get_result_df(models, model_names, X_train_tmk, y_train_tmk, X_valid, y_valid)
results

              Accuracy  precision    recall        f1       roc
LogiReg       0.676630   0.005981  0.714286  0.011862  0.695407
DecisionTree  0.480202   0.002985  0.571429  0.005939  0.525691
RandomFore    0.939053   0.006579  0.142857  0.012579  0.542040
LGBM          0.940217   0.006711  0.142857  0.012821  0.542624
SVC           0.684394   0.006127  0.714286  0.012151  0.699299

In [90]:
X_test

,car_model,sharing_type,age_group,has_previous_accident,cumulative_use_count,b2b,accident_ratio,pf_type,socarpass,socarsave,...,insure_cost,accident_location,car_part1,car_part2,repair_cnt,acc_type1,insurance_site_aid_YN,police_site_aid_YN,total_prsn_cnt,test_set
1,1,0,4,0,4,0,0,3,1,0,...,0,1,1,1,2,1,1,1,0,1
2,1,0,4,1,4,0,100,3,1,0,...,12925040,3,1,0,2,1,1,1,0,1
5,2,1,3,0,1,0,100,1,0,1,...,4777030,1,1,0,1,1,1,1,0,1
7,3,1,3,0,4,0,100,3,1,0,...,250000,2,0,0,1,1,1,1,1,1
9,2,0,4,0,4,0,100,1,0,1,...,0,2,1,0,1,0,0,0,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15978,1,0,2,0,4,0,100,3,0,0,...,1708720,0,0,0,1,1,1,1,1,1
15983,2,0,1,0,4,0,100,3,0,0,...,0,4,1,0,1,0,0,0,-1,1
15984,2,0,2,0,1,0,100,1,0,0,...,810230,0,0,0,1,1,1,1,1,1
15992,2,0,2,0,2,0,100,3,0,0,...,0,4,0,0,2,0,0,0,-1,1
15997,2,1,2,0,4,0,100,1,0,0,...,0,0,0,0,1,0,0,0,-1,1

In [92]:
# ------- 테스트셋 적용하기 -------

# 테스트셋 적용 
# PCA / ss 

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

df_scaled = scaler.transform(X_test)

pca = PCA(n_components=3)
pca.fit(df_scaled)
df_pca = pca.transform(df_scaled)

pca_columns = ['component_1','component_2','component_3']

DF_pca = pd.DataFrame(df_pca, columns=pca_columns)
DF_pca['target'] = y_target 
DF_pca.head()

ValueError: Shape of passed values is (3121, 3), indices imply (3121, 2)

In [ ]:
# ssscale / pca(n=3) / smote-tomek

In [ ]:
# ssscale / pca(n=3) / smote-tomek / repair_cost 전처리

In [ ]:
# robust / pca(n=3) / smote-tomek